insert into Product (productID, Description, Price, Weight) values (1, 'Crackers - Soda / Saltins', '32.93', 74);
insert into Product (productID, Description, Price, Weight) values (2, 'Puree - Blackcurrant', '42.88', 799);
insert into Product (productID, Description, Price, Weight) values (3, 'Milk 2% 500 Ml', '6.67', 619);
insert into Product (productID, Description, Price, Weight) values (4, 'Cups 10oz Trans', '11.24', 729);
insert into Product (productID, Description, Price, Weight) values (5, 'Cheese - Cheddarsliced', '29.75', 941);
insert into Product (productID, Description, Price, Weight) values (6, 'Cheese - Havarti, Roasted Garlic', '43.76', 526);
insert into Product (productID, Description, Price, Weight) values (7, 'Cheese - Comtomme', '7.11', 505);
insert into Product (productID, Description, Price, Weight) values (8, 'Cocoa Butter', '38.81', 563);
insert into Product (productID, Description, Price, Weight) values (9, 'Bag - Clear 7 Lb', '41.07', 503);
insert into Product (productID, Description, Price, Weight) values (10, 'Graham Cracker Mix', '36.88', 444);
insert into Product (productID, Description, Price, Weight) values (11, 'Cheese - Augre Des Champs', '43.38', 560);
insert into Product (productID, Description, Price, Weight) values (12, 'Dc - Sakura Fu', '12.12', 357);
insert into Product (productID, Description, Price, Weight) values (13, 'Liners - Banana, Paper', '12.73', 880);
insert into Product (productID, Description, Price, Weight) values (14, 'Scallops - U - 10', '14.42', 117);
insert into Product (productID, Description, Price, Weight) values (15, 'V8 Pet', '20.08', 532);
insert into Product (productID, Description, Price, Weight) values (16, 'Beef - Bones, Marrow', '10.05', 952);
insert into Product (productID, Description, Price, Weight) values (17, 'Stock - Beef, White', '10.79', 675);
insert into Product (productID, Description, Price, Weight) values (18, 'Lettuce - Romaine', '5.79', 592);
insert into Product (productID, Description, Price, Weight) values (19, 'Breadfruit', '26.21', 347);
insert into Product (productID, Description, Price, Weight) values (20, 'Filter - Coffee', '37.12', 147);
insert into Product (productID, Description, Price, Weight) values (21, 'Cookie Dough - Oatmeal Rasin', '14.50', 51);
insert into Product (productID, Description, Price, Weight) values (22, 'Mushroom - Enoki, Dry', '17.87', 725);
insert into Product (productID, Description, Price, Weight) values (23, 'Squeeze Bottle', '33.26', 695);
insert into Product (productID, Description, Price, Weight) values (24, 'Table Cloth 72x144 White', '6.84', 226);
insert into Product (productID, Description, Price, Weight) values (25, 'Chicken - Base', '18.33', 910);
insert into Product (productID, Description, Price, Weight) values (26, 'Veal Inside - Provimi', '18.03', 95);
insert into Product (productID, Description, Price, Weight) values (27, 'Wine - Red, Harrow Estates, Cab', '14.19', 508);
insert into Product (productID, Description, Price, Weight) values (28, 'Irish Cream - Baileys', '35.95', 401);
insert into Product (productID, Description, Price, Weight) values (29, 'Puree - Guava', '10.68', 428);
insert into Product (productID, Description, Price, Weight) values (30, 'Cheese - Goat', '32.06', 77);
insert into Product (productID, Description, Price, Weight) values (31, 'Neckerchief Blck', '39.31', 477);
insert into Product (productID, Description, Price, Weight) values (32, 'Lid - 10,12,16 Oz', '14.74', 722);
insert into Product (productID, Description, Price, Weight) values (33, 'Limes', '41.18', 773);
insert into Product (productID, Description, Price, Weight) values (34, 'Flour Dark Rye', '15.45', 243);
insert into Product (productID, Description, Price, Weight) values (35, 'Green Scrubbie Pad H.duty', '9.40', 434);
insert into Product (productID, Description, Price, Weight) values (36, 'Ice Cream - Fudge Bars', '11.09', 767);
insert into Product (productID, Description, Price, Weight) values (37, 'Coffee - Frthy Coffee Crisp', '41.74', 161);
insert into Product (productID, Description, Price, Weight) values (38, 'Puree - Mocha', '24.01', 750);
insert into Product (productID, Description, Price, Weight) values (39, 'Monkfish - Fresh', '40.95', 442);
insert into Product (productID, Description, Price, Weight) values (40, 'Apron', '23.01', 92);
insert into Product (productID, Description, Price, Weight) values (41, 'Cake - Mini Potato Pancake', '35.76', 259);
insert into Product (productID, Description, Price, Weight) values (42, 'Table Cloth 53x53 White', '40.30', 189);
insert into Product (productID, Description, Price, Weight) values (43, 'Wine - Casablanca Valley', '8.23', 349);
insert into Product (productID, Description, Price, Weight) values (44, 'Juice - Prune', '12.48', 128);
insert into Product (productID, Description, Price, Weight) values (45, 'Table Cloth 120 Round White', '15.81', 817);
insert into Product (productID, Description, Price, Weight) values (46, 'Sping Loaded Cup Dispenser', '24.71', 999);
insert into Product (productID, Description, Price, Weight) values (47, 'Shrimp - 16/20, Iqf, Shell On', '20.42', 998);
insert into Product (productID, Description, Price, Weight) values (48, 'Smoked Tongue', '17.81', 497);
insert into Product (productID, Description, Price, Weight) values (49, 'Plums - Red', '23.14', 203);
insert into Product (productID, Description, Price, Weight) values (50, 'Salmon - Canned', '39.70', 875);
insert into Product (productID, Description, Price, Weight) values (51, 'Marjoram - Fresh', '8.32', 440);
insert into Product (productID, Description, Price, Weight) values (52, 'Fireball Whisky', '37.65', 104);
insert into Product (productID, Description, Price, Weight) values (53, 'Turkey Tenderloin Frozen', '36.82', 273);
insert into Product (productID, Description, Price, Weight) values (54, 'Duck - Whole', '32.82', 329);
insert into Product (productID, Description, Price, Weight) values (55, 'Cheese - Cheddar, Medium', '38.29', 216);
insert into Product (productID, Description, Price, Weight) values (56, 'Wine - Touraine Azay - Le - Rideau', '29.98', 345);
insert into Product (productID, Description, Price, Weight) values (57, 'Lentils - Green, Dry', '33.65', 234);
insert into Product (productID, Description, Price, Weight) values (58, 'Flour - Corn, Fine', '17.76', 588);
insert into Product (productID, Description, Price, Weight) values (59, 'Pepper - Cubanelle', '11.93', 728);
insert into Product (productID, Description, Price, Weight) values (60, 'Veal - Chops, Split, Frenched', '27.04', 650);
insert into Product (productID, Description, Price, Weight) values (61, 'Tea Leaves - Oolong', '16.24', 734);
insert into Product (productID, Description, Price, Weight) values (62, 'Eggplant - Baby', '7.25', 286);
insert into Product (productID, Description, Price, Weight) values (63, 'Sauce - Salsa', '19.75', 844);
insert into Product (productID, Description, Price, Weight) values (64, 'Wine - Piper Heidsieck Brut', '6.09', 723);
insert into Product (productID, Description, Price, Weight) values (65, 'Yogurt - Plain', '37.14', 241);
insert into Product (productID, Description, Price, Weight) values (66, 'Tuna - Canned, Flaked, Light', '27.23', 119);
insert into Product (productID, Description, Price, Weight) values (67, 'Sugar - Cubes', '22.48', 790);
insert into Product (productID, Description, Price, Weight) values (68, 'Potatoes - Fingerling 4 Oz', '11.55', 364);
insert into Product (productID, Description, Price, Weight) values (69, 'Tea - Lemon Scented', '40.54', 406);
insert into Product (productID, Description, Price, Weight) values (70, 'Salmon - Canned', '28.08', 588);
insert into Product (productID, Description, Price, Weight) values (71, 'Duck - Whole', '12.51', 718);
insert into Product (productID, Description, Price, Weight) values (72, 'Potato - Sweet', '8.74', 920);
insert into Product (productID, Description, Price, Weight) values (73, 'Sauce - Black Current, Dry Mix', '14.34', 120);
insert into Product (productID, Description, Price, Weight) values (74, 'Pear - Packum', '33.66', 973);
insert into Product (productID, Description, Price, Weight) values (75, 'Lemon Balm - Fresh', '35.14', 249);
insert into Product (productID, Description, Price, Weight) values (76, 'Cake - Cheese Cake 9 Inch', '17.66', 461);
insert into Product (productID, Description, Price, Weight) values (77, 'Hersey Shakes', '5.92', 111);
insert into Product (productID, Description, Price, Weight) values (78, 'Vegetable - Base', '9.65', 742);
insert into Product (productID, Description, Price, Weight) values (79, 'Cherries - Maraschino,jar', '32.91', 92);
insert into Product (productID, Description, Price, Weight) values (80, 'Salmon - Atlantic, Fresh, Whole', '38.23', 661);
insert into Product (productID, Description, Price, Weight) values (81, 'Island Oasis - Ice Cream Mix', '34.84', 505);
insert into Product (productID, Description, Price, Weight) values (82, 'Cafe Royale', '38.67', 271);
insert into Product (productID, Description, Price, Weight) values (83, 'Pork - Tenderloin, Fresh', '12.08', 601);
insert into Product (productID, Description, Price, Weight) values (84, 'Cake - Night And Day Choclate', '18.93', 603);
insert into Product (productID, Description, Price, Weight) values (85, 'Sugar - Palm', '34.10', 906);
insert into Product (productID, Description, Price, Weight) values (86, 'Dc - Frozen Momji', '26.94', 212);
insert into Product (productID, Description, Price, Weight) values (87, 'Wine - Gato Negro Cabernet', '42.53', 840);
insert into Product (productID, Description, Price, Weight) values (88, 'Soup Campbells - Tomato Bisque', '10.29', 112);
insert into Product (productID, Description, Price, Weight) values (89, 'Soup - Campbells Asian Noodle', '9.90', 51);
insert into Product (productID, Description, Price, Weight) values (90, 'Icecream - Dstk Cml And Fdg', '34.78', 355);
insert into Product (productID, Description, Price, Weight) values (91, 'Chilli Paste, Ginger Garlic', '19.35', 969);
insert into Product (productID, Description, Price, Weight) values (92, 'Veal - Round, Eye Of', '19.01', 176);
insert into Product (productID, Description, Price, Weight) values (93, 'Wine - Valpolicella Masi', '29.87', 367);
insert into Product (productID, Description, Price, Weight) values (94, 'Cheese - Le Cheve Noir', '30.26', 900);
insert into Product (productID, Description, Price, Weight) values (95, 'Silicone Parch. 16.3x24.3', '28.39', 894);
insert into Product (productID, Description, Price, Weight) values (96, 'Lettuce - Belgian Endive', '25.86', 351);
insert into Product (productID, Description, Price, Weight) values (97, 'Juice Peach Nectar', '37.84', 251);
insert into Product (productID, Description, Price, Weight) values (98, 'Ostrich - Prime Cut', '40.67', 63);
insert into Product (productID, Description, Price, Weight) values (99, 'Bacardi Mojito', '21.95', 943);
insert into Product (productID, Description, Price, Weight) values (100, 'Sprouts - Alfalfa', '26.07', 973);
